# Generated by Django 2.2.6 on 2020-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0002_attendance_attendancereport_feedbackstaffs_feedbackstudent_leavereportstaffs_leavereportstudent_noti'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
    ]
